name: test-project
on: [push]
jobs:
  run-tests:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python manage.py migrate
      - run: python manage.py test