# Generated by Django 3.0.7 on 2022-08-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_now', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbioinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userbioinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userbioinfo',
            name='last_cert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
