# Generated by Django 3.0.7 on 2022-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_now', '0002_auto_20220816_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbioinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
