# Generated by Django 3.0.7 on 2022-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_now', '0003_auto_20220816_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbioinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
