# Generated by Django 3.0.7 on 2022-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_now', '0004_auto_20220816_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbioinfo',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='userbioinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
